# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Fish

on:
Â  push:
Â  Â  branches:
Â  Â  Â  - main
Â  workflow_dispatch:

jobs:
Â  build:
Â  Â  runs-on: windows-latest
Â  Â  permissions:
Â  Â  Â  contents: read #This is required for actions/checkout

Â  Â  steps:
Â  Â  Â  - uses: actions/checkout@v4

Â  Â  Â  - name: Set up .NET Core
Â  Â  Â  Â  uses: actions/setup-dotnet@v4
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  dotnet-version: '10.x'

Â  Â  Â  - name: Build with dotnet
Â  Â  Â  Â  run: dotnet build --configuration Release
Â  Â  Â  Â  working-directory: RiverController/RiverController # ğŸ‘ˆ ã€é‡è¦ã€‘ã“ã“ã‚’è¿½åŠ 
        
Â  Â  Â  - name: dotnet publish
Â  Â  Â  Â  run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
Â  Â  Â  Â  working-directory: RiverController/RiverController # ğŸ‘ˆ ã€é‡è¦ã€‘ã“ã“ã‚’è¿½åŠ 

Â  Â  Â  - name: Upload artifact for deployment job
Â  Â  Â  Â  uses: actions/upload-artifact@v4
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  name: .net-app
Â  Â  Â  Â  Â  path: ${{env.DOTNET_ROOT}}/myapp

Â  deploy:
Â  Â  runs-on: windows-latest
Â  Â  needs: build
Â  Â  permissions:
Â  Â  Â  id-token: write #This is required for requesting the JWT
Â  Â  Â  contents: read #This is required for actions/checkout

Â  Â  steps:
Â  Â  Â  - name: Download artifact from build job
Â  Â  Â  Â  uses: actions/download-artifact@v4
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  name: .net-app
Â  Â  Â  
Â  Â  Â  - name: Login to Azure
Â  Â  Â  Â  uses: azure/login@v2
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4BFC1FEF237E404F8CC54A9C06629577 }}
Â  Â  Â  Â  Â  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_76A556BA3A1444019A5FB83E89B292E3 }}
Â  Â  Â  Â  Â  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C90192BC2DED43EAA7C641C5DF1C945C }}

Â  Â  Â  - name: Deploy to Azure Web App
Â  Â  Â  Â  id: deploy-to-webapp
Â  Â  Â  Â  uses: azure/webapps-deploy@v3
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  app-name: 'Fish'
Â  Â  Â  Â  Â  slot-name: 'Production'
Â  Â  Â  Â  Â  package: .